[project]
name = "easy-key-annotation"
version = "0.1.0"
description = "Easy annotation based on a key column"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "pandas>=2.0",
]
